/**
 * Verification Service (KYC)
 * Manages driver/passenger verification requests and document reviews
 */

import { apiClient } from '@/lib/api/client';

// Types
export type VerificationStatus = 'pending' | 'approved' | 'rejected' | 'needs_review';
export type DocumentType = 'id' | 'license' | 'insurance' | 'background_check' | 'vehicle_registration' | 'selfie' | 'business_permit';
export type RiskLevel = 'low' | 'medium' | 'high';

export interface VerificationRequest {
  id: string;
  applicant: {
    id: string;
    name: string;
    email: string;
    phone: string;
    role: 'driver' | 'passenger' | 'operator';
    avatarUrl?: string;
  };
  status: VerificationStatus;
  documents: VerificationDocument[];
  submittedAt: string;
  reviewedAt?: string;
  reviewedBy?: {
    id: string;
    name: string;
  };
  reviewNotes?: string;
  rejectionReason?: string;
  riskFlags: RiskFlag[];
  automatedScore: number; // 0-100
  priority: 'low' | 'normal' | 'high' | 'urgent';
}

export interface VerificationDocument {
  id: string;
  type: DocumentType;
  status: 'pending' | 'verified' | 'rejected';
  fileUrl: string;
  thumbnailUrl?: string;
  uploadedAt: string;
  extractedData?: Record<string, string>;
  verificationNotes?: string;
}

export interface RiskFlag {
  id: string;
  type: string;
  severity: RiskLevel;
  description: string;
  autoGenerated: boolean;
  createdAt: string;
}

export interface VerificationStats {
  totalPending: number;
  totalApproved: number;
  totalRejected: number;
  averageReviewTime: number; // minutes
  byType: Record<DocumentType, number>;
  riskDistribution: {
    low: number;
    medium: number;
    high: number;
  };
  dailySubmissions: Array<{
    date: string;
    count: number;
  }>;
}

export interface ReviewAction {
  action: 'approve' | 'reject' | 'request_more_info';
  notes?: string;
  rejectionReason?: string;
  documentDecisions?: Array<{
    documentId: string;
    decision: 'approve' | 'reject';
    notes?: string;
  }>;
}

// API Endpoints
const VERIFICATION_ENDPOINTS = {
  // Requests
  getRequests: '/api/verification/requests',
  getRequest: (id: string) => `/api/verification/requests/${id}`,
  submitReview: (id: string) => `/api/verification/requests/${id}/review`,
  addNote: (id: string) => `/api/verification/requests/${id}/notes`,
  
  // Documents
  getDocument: (id: string) => `/api/verification/documents/${id}`,
  verifyDocument: (id: string) => `/api/verification/documents/${id}/verify`,
  rejectDocument: (id: string) => `/api/verification/documents/${id}/reject`,
  
  // Stats
  getStats: '/api/verification/stats',
  
  // Batch
  batchApprove: '/api/verification/batch/approve',
  batchReject: '/api/verification/batch/reject',
};

// Mock data for development
const mockDocuments: VerificationDocument[] = [
  {
    id: 'DOC-001',
    type: 'id',
    status: 'verified',
    fileUrl: '/api/placeholder/400/600',
    thumbnailUrl: '/api/placeholder/200/300',
    uploadedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    extractedData: {
      'Full Name': 'Juan Dela Cruz',
      'ID Number': '1234-5678-9012',
      'Date of Birth': '1990-05-15',
      'Address': '123 Main St, Manila',
    },
  },
  {
    id: 'DOC-002',
    type: 'license',
    status: 'verified',
    fileUrl: '/api/placeholder/600/400',
    thumbnailUrl: '/api/placeholder/300/200',
    uploadedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    extractedData: {
      'License Number': 'N01-12-345678',
      'Expiry Date': '2026-08-20',
      'Restrictions': 'None',
      'Class': 'Professional',
    },
  },
  {
    id: 'DOC-003',
    type: 'insurance',
    status: 'pending',
    fileUrl: '/api/placeholder/400/600',
    thumbnailUrl: '/api/placeholder/200/300',
    uploadedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    extractedData: {
      'Policy Number': 'INS-2025-001234',
      'Valid Until': '2025-12-31',
      'Coverage': 'Comprehensive',
    },
  },
];

const mockRiskFlags: RiskFlag[] = [
  {
    id: 'RF-001',
    type: 'document_mismatch',
    severity: 'medium',
    description: 'Name on ID does not exactly match application name',
    autoGenerated: true,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'RF-002',
    type: 'suspicious_document',
    severity: 'high',
    description: 'Document image shows signs of possible tampering',
    autoGenerated: true,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];

const mockRequests: VerificationRequest[] = [
  {
    id: 'VR-001',
    applicant: {
      id: 'U-001',
      name: 'Juan Dela Cruz',
      email: 'juan.delacruz@email.com',
      phone: '+63 912 345 6789',
      role: 'driver',
    },
    status: 'pending',
    documents: [
      { ...mockDocuments[0], id: 'DOC-001-1' },
      { ...mockDocuments[1], id: 'DOC-001-2' },
      { ...mockDocuments[2], id: 'DOC-001-3' },
    ],
    submittedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    riskFlags: [mockRiskFlags[0]],
    automatedScore: 78,
    priority: 'normal',
  },
  {
    id: 'VR-002',
    applicant: {
      id: 'U-002',
      name: 'Maria Santos',
      email: 'maria.santos@email.com',
      phone: '+63 923 456 7890',
      role: 'driver',
    },
    status: 'pending',
    documents: [
      {
        id: 'DOC-002-1',
        type: 'id',
        status: 'pending',
        fileUrl: '/api/placeholder/400/600',
        thumbnailUrl: '/api/placeholder/200/300',
        uploadedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      },
      {
        id: 'DOC-002-2',
        type: 'license',
        status: 'pending',
        fileUrl: '/api/placeholder/600/400',
        thumbnailUrl: '/api/placeholder/300/200',
        uploadedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      },
    ],
    submittedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    riskFlags: [],
    automatedScore: 92,
    priority: 'high',
  },
  {
    id: 'VR-003',
    applicant: {
      id: 'U-003',
      name: 'Pedro Reyes',
      email: 'pedro.reyes@email.com',
      phone: '+63 934 567 8901',
      role: 'driver',
    },
    status: 'pending',
    documents: [
      {
        id: 'DOC-003-1',
        type: 'id',
        status: 'verified',
        fileUrl: '/api/placeholder/400/600',
        thumbnailUrl: '/api/placeholder/200/300',
        uploadedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      },
      {
        id: 'DOC-003-2',
        type: 'license',
        status: 'verified',
        fileUrl: '/api/placeholder/600/400',
        thumbnailUrl: '/api/placeholder/300/200',
        uploadedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      },
      {
        id: 'DOC-003-3',
        type: 'background_check',
        status: 'pending',
        fileUrl: '/api/placeholder/400/600',
        thumbnailUrl: '/api/placeholder/200/300',
        uploadedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      },
    ],
    submittedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    riskFlags: [mockRiskFlags[1]],
    automatedScore: 45,
    priority: 'urgent',
  },
  {
    id: 'VR-004',
    applicant: {
      id: 'U-004',
      name: 'Ana Lopez',
      email: 'ana.lopez@email.com',
      phone: '+63 945 678 9012',
      role: 'operator',
    },
    status: 'approved',
    documents: [
      {
        id: 'DOC-004-1',
        type: 'id',
        status: 'verified',
        fileUrl: '/api/placeholder/400/600',
        thumbnailUrl: '/api/placeholder/200/300',
        uploadedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
      },
      {
        id: 'DOC-004-2',
        type: 'business_permit',
        status: 'verified',
        fileUrl: '/api/placeholder/400/600',
        thumbnailUrl: '/api/placeholder/200/300',
        uploadedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
      },
    ],
    submittedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    reviewedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    reviewedBy: {
      id: 'ADMIN-001',
      name: 'Admin User',
    },
    reviewNotes: 'All documents verified. Clean background check.',
    riskFlags: [],
    automatedScore: 95,
    priority: 'normal',
  },
  {
    id: 'VR-005',
    applicant: {
      id: 'U-005',
      name: 'Carlos Mendoza',
      email: 'carlos.mendoza@email.com',
      phone: '+63 956 789 0123',
      role: 'driver',
    },
    status: 'rejected',
    documents: [
      {
        id: 'DOC-005-1',
        type: 'id',
        status: 'rejected',
        fileUrl: '/api/placeholder/400/600',
        thumbnailUrl: '/api/placeholder/200/300',
        uploadedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
        verificationNotes: 'Document appears to be expired',
      },
      {
        id: 'DOC-005-2',
        type: 'license',
        status: 'rejected',
        fileUrl: '/api/placeholder/600/400',
        thumbnailUrl: '/api/placeholder/300/200',
        uploadedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
        verificationNotes: 'License suspended',
      },
    ],
    submittedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    reviewedAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    reviewedBy: {
      id: 'ADMIN-001',
      name: 'Admin User',
    },
    reviewNotes: 'Multiple issues with submitted documents.',
    rejectionReason: 'Invalid/expired documents submitted',
    riskFlags: [
      {
        id: 'RF-003',
        type: 'expired_document',
        severity: 'high',
        description: 'ID card has expired',
        autoGenerated: true,
        createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
      },
      {
        id: 'RF-004',
        type: 'suspended_license',
        severity: 'high',
        description: 'Driver license is currently suspended',
        autoGenerated: false,
        createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
      },
    ],
    automatedScore: 15,
    priority: 'high',
  },
];

// Service functions
export const verificationService = {
  // Requests
  async getRequests(params?: {
    status?: VerificationStatus;
    documentType?: DocumentType;
    search?: string;
    priority?: string;
    page?: number;
    limit?: number;
  }): Promise<{ items: VerificationRequest[]; total: number }> {
    // TODO: Replace with actual API call
    // return apiClient.get(VERIFICATION_ENDPOINTS.getRequests, { params });
    return new Promise((resolve) => {
      setTimeout(() => {
        let filtered = [...mockRequests];
        
        if (params?.status) {
          filtered = filtered.filter((r) => r.status === params.status);
        }
        if (params?.documentType) {
          filtered = filtered.filter((r) =>
            r.documents.some((d) => d.type === params.documentType)
          );
        }
        if (params?.search) {
          const search = params.search.toLowerCase();
          filtered = filtered.filter(
            (r) =>
              r.applicant.name.toLowerCase().includes(search) ||
              r.applicant.email.toLowerCase().includes(search) ||
              r.id.toLowerCase().includes(search)
          );
        }
        if (params?.priority) {
          filtered = filtered.filter((r) => r.priority === params.priority);
        }
        
        resolve({ items: filtered, total: filtered.length });
      }, 500);
    });
  },

  async getRequest(id: string): Promise<VerificationRequest | null> {
    // return apiClient.get<VerificationRequest>(VERIFICATION_ENDPOINTS.getRequest(id));
    return new Promise((resolve) => {
      setTimeout(() => {
        const request = mockRequests.find((r) => r.id === id);
        resolve(request || null);
      }, 300);
    });
  },

  async submitReview(id: string, action: ReviewAction): Promise<VerificationRequest> {
    // return apiClient.post<VerificationRequest>(VERIFICATION_ENDPOINTS.submitReview(id), action);
    return new Promise((resolve) => {
      setTimeout(() => {
        const request = mockRequests.find((r) => r.id === id);
        if (request) {
          request.status = action.action === 'approve' ? 'approved' : action.action === 'reject' ? 'rejected' : 'needs_review';
          request.reviewedAt = new Date().toISOString();
          request.reviewedBy = { id: 'ADMIN-001', name: 'Current Admin' };
          request.reviewNotes = action.notes;
          request.rejectionReason = action.rejectionReason;
        }
        resolve(request!);
      }, 500);
    });
  },

  async addNote(id: string, note: string): Promise<void> {
    // return apiClient.post(VERIFICATION_ENDPOINTS.addNote(id), { note });
    return new Promise((resolve) => {
      setTimeout(() => {
        const request = mockRequests.find((r) => r.id === id);
        if (request) {
          request.reviewNotes = request.reviewNotes
            ? `${request.reviewNotes}\n${new Date().toISOString()}: ${note}`
            : note;
        }
        resolve();
      }, 300);
    });
  },

  // Documents
  async verifyDocument(documentId: string, notes?: string): Promise<void> {
    // return apiClient.post(VERIFICATION_ENDPOINTS.verifyDocument(documentId), { notes });
    return new Promise((resolve) => {
      setTimeout(() => {
        mockRequests.forEach((req) => {
          const doc = req.documents.find((d) => d.id === documentId);
          if (doc) {
            doc.status = 'verified';
            doc.verificationNotes = notes;
          }
        });
        resolve();
      }, 300);
    });
  },

  async rejectDocument(documentId: string, reason: string): Promise<void> {
    // return apiClient.post(VERIFICATION_ENDPOINTS.rejectDocument(documentId), { reason });
    return new Promise((resolve) => {
      setTimeout(() => {
        mockRequests.forEach((req) => {
          const doc = req.documents.find((d) => d.id === documentId);
          if (doc) {
            doc.status = 'rejected';
            doc.verificationNotes = reason;
          }
        });
        resolve();
      }, 300);
    });
  },

  // Stats
  async getStats(): Promise<VerificationStats> {
    // return apiClient.get<VerificationStats>(VERIFICATION_ENDPOINTS.getStats);
    return new Promise((resolve) => {
      setTimeout(() => {
        const pending = mockRequests.filter((r) => r.status === 'pending');
        const approved = mockRequests.filter((r) => r.status === 'approved');
        const rejected = mockRequests.filter((r) => r.status === 'rejected');

        resolve({
          totalPending: pending.length,
          totalApproved: approved.length,
          totalRejected: rejected.length,
          averageReviewTime: 45,
          byType: {
            id: 5,
            license: 4,
            insurance: 3,
            background_check: 2,
            vehicle_registration: 1,
            selfie: 0,
            business_permit: 1,
          },
          riskDistribution: {
            low: pending.filter((r) => r.automatedScore >= 80).length,
            medium: pending.filter((r) => r.automatedScore >= 50 && r.automatedScore < 80).length,
            high: pending.filter((r) => r.automatedScore < 50).length,
          },
          dailySubmissions: [
            { date: '2025-02-10', count: 3 },
            { date: '2025-02-11', count: 5 },
            { date: '2025-02-12', count: 2 },
            { date: '2025-02-13', count: 4 },
            { date: '2025-02-14', count: 6 },
            { date: '2025-02-15', count: 3 },
            { date: '2025-02-16', count: 2 },
          ],
        });
      }, 300);
    });
  },

  // Batch operations
  async batchApprove(ids: string[]): Promise<{ success: number; failed: number }> {
    // return apiClient.post(VERIFICATION_ENDPOINTS.batchApprove, { ids });
    return new Promise((resolve) => {
      setTimeout(() => {
        ids.forEach((id) => {
          const request = mockRequests.find((r) => r.id === id);
          if (request) {
            request.status = 'approved';
            request.reviewedAt = new Date().toISOString();
            request.reviewedBy = { id: 'ADMIN-001', name: 'Current Admin' };
          }
        });
        resolve({ success: ids.length, failed: 0 });
      }, 500);
    });
  },

  async batchReject(ids: string[], reason: string): Promise<{ success: number; failed: number }> {
    // return apiClient.post(VERIFICATION_ENDPOINTS.batchReject, { ids, reason });
    return new Promise((resolve) => {
      setTimeout(() => {
        ids.forEach((id) => {
          const request = mockRequests.find((r) => r.id === id);
          if (request) {
            request.status = 'rejected';
            request.reviewedAt = new Date().toISOString();
            request.reviewedBy = { id: 'ADMIN-001', name: 'Current Admin' };
            request.rejectionReason = reason;
          }
        });
        resolve({ success: ids.length, failed: 0 });
      }, 500);
    });
  },
};

export default verificationService;
